# default-values Settings
defaultGameMode: solo
defaultInterval: 100
defaultCount: 20

#SQL Settings
enabled-sql: false
host: localhost
port: 3306
username: root
password: password
teams_table: teams
members_table: team_members

